deployment:
  repo: diogenes1oliveira/kerberos-auth-proxy
  version: 0.1.0a15
service:
  type: ClusterIP
mitm:
  caKey: ""
  caPem: ""
  authPassword: ""
  env: {}
trustCAs: {}
kerberos:
  krb5Conf: ""
  keytabs: {}
