---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kerberos-auth-proxy.kerberos-keytabs-name" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
{{- with .Values.kerberos.keytabs }}
{{- range $name, $content := . }}
  {{ $name }}: {{ $content | quote }}
{{- end }}
{{- else }}
  {}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
type: Opaque
metadata:
  name: {{ template "kerberos-auth-proxy.kerberos-conf-name" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  krb5.conf: {{ .Values.kerberos.krb5Conf | quote }}
