{{- $keytabNames := (.Values.kerberos.keytabs | keys | sortAlpha) -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kerberos-auth-proxy.mitm-auth-name" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  auth: |
    IyB1c2Vycwo=
    {{- if or (not .Values.mitm.authPassword) (not $keytabNames) }}
    {{- range $i, $name := (.Values.kerberos.keytabs | keys | sortAlpha) }}
    {{- (htpasswd $name $.Values.mitm.authPassword) | indent 4 | b64enc }}
    {{- end }}
    {{- end }}
