{{- $keytabNames := (.Values.kerberos.keytabs | keys | sortAlpha) -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kerberos-auth-proxy.mitm-auth-name" . }}
  namespace: {{ .Release.Namespace | quote }}
stringData:
  auth: |
    {{- if and .Values.mitm.authPassword $keytabNames }}
    {{- range $i, $name := $keytabNames }}
    {{- (htpasswd (trimSuffix ".keytab" $name) $.Values.mitm.authPassword) | nindent 4 }}
    {{- end }}
    {{- else }}
    # no users
    {{- end }}
